fail_fast: false

repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.3.0
#    hooks:
#      - id: end-of-file-fixer
#      - id: trailing-whitespace
#      - id: check-case-conflict
#      - id: check-json
#      - id: check-yaml

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.18.4
    hooks:
      - id: check-jsonschema
        files: ^samples/schema-demo-.*\.(yml|yaml)$
        args: ["--schemafile", "schema.json"]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.50.1
    hooks:
      - id: golangci-lint
        require_serial: true
